dist: xenial
language: python
python:
  - "3.7-dev"
  - "3.8-dev"
  - "3.7"
  - "nightly"

# Disable sudo to speed up the build
sudo: false
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test --cov-config=.coveragerc --cov=./ --cov-report xml tests/
# report coverage
after_success:
- codecov
