[build]
publish = "site/"
command = """
restore_home_cache ".cache" "pip cache" &&
restore_cwd_cache '.venv' 'python virtualenv' &&
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install &&
mkdocs build &&
cp mkdocs/_redirects site/_redirects
"""
